name="Lays"
image="lays-blue.jpg"
type="food"
defaultVariant=0

[variants.blue]
stock=5
price=20
category="snack"
image="lays-blue.jpg"
name="Blue"

[variants.green]
stock=5
price=20
category="snack"
image="lays-green.png"
name="Green"

[variants.yellow]
stock=5
price=20
category="snack"
image="lays-yellow.jpg"
name="Yellow"