name="Milkshake"
image="oreo-milkshake.jpg"
type="food"
defaultVariant=0

[variants.oreo]
stock=5
price=50
category="refreshment"
image="oreo-milkshake.jpg"
name="Oreo"

[variants.strawberry]
stock=5
price=70
category="refreshment"
image="strawberry-milkshake.jpg"
name="Strawberry"

[variants.apple]
stock=5
price=70
category="refreshment"
image="apple-milkshake.jpg"
name="Apple"
