name="Noodles"
image="noodles.jpg"
type="food"
defaultVariant=0

[variants.veg]
stock=5
price=60
category="veg"
image="noodles.jpg"
name="Veg"

[variants.egg]
stock=5
price=80
category="non-veg"
image="noodles.jpg"
name="Egg"

[variants.chicken]
stock=5
price=110
category="non-veg"
image="noodles.jpg"
name="Chicken"