name="Puffs"
image="puffs.jpg"
type="food"
defaultVariant=0

[variants.veg]
stock=5
price=15
category="veg"
image="puffs.jpg"
name="Veg"

[variants.paneer]
stock=5
price=25
category="veg"
image="puffs.jpg"
name="Paneer"

[variants.egg]
stock=5
price=20
category="non-veg"
image="puffs.jpg"
name="Egg"

[variants.chicken]
stock=5
price=25
category="non-veg"
image="puffs.jpg"
name="Chicken"